# Generated by Django 3.0.5 on 2020-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customers', models.CharField(max_length=50)),
                ('address_customers', models.TextField()),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
